# fly.toml app configuration file generated for kangnam-chatbot on 2025-05-12T00:24:01+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kangnam-chatbot'
primary_region = 'nrt'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 500

[[services]]
  protocol = 'tcp'
  internal_port = 8000

  [[services.ports]]
    port = 8000
    handlers = ['http']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
