# Streamlit 비밀 파일
# 이 파일은 Streamlit Cloud에서 환경 변수로 설정됩니다

# FastAPI 백엔드 URL (배포 후 실제 URL로 교체)
BACKEND_URL = "https://kangnam-backend-88199591627.asia-east1.run.app/api"

# 기타 필요한 API 키

SUPABASE_URL = "https://gvyxdsrjhubzfewtodan.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2eXhkc3JqaHViemZld3RvZGFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MzMxODEsImV4cCI6MjA2MjIwOTE4MX0.cPIX14jA0z0Y7hZaa4CCteuedAw4Jan5Ck8Vyci7sAo"
