# Streamlit 비밀 파일
# 이 파일은 Streamlit Cloud에서 환경 변수로 설정됩니다

# FastAPI 백엔드 URL (배포 후 실제 URL로 교체)
BACKEND_URL = "https://kangnam-backend-xxx.run.app"

# 기타 필요한 API 키
# SUPABASE_URL = "your_supabase_url"
# SUPABASE_KEY = "your_supabase_key" 